@startuml
actor "Administrador" as Admin
actor "Paciente" as Paciente

rectangle "Sistema de Gestión de Clientes de Optica" {
    (Crear Paciente) as UC1
    (Actualizar Perfil) as UC2
    (Eliminar Paciente) as UC3
    (Listar Pacientes) as UC4

    Admin -up-> UC1
    Admin -up-> UC2
    Admin -up-> UC3
    Admin -up-> UC4
}

@enduml
